"""Add is_read and status to contacts

Revision ID: f7b5e631ed28
Revises: 007_add_service_featured_slug
Create Date: 2026-03-08 20:36:02.045452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f7b5e631ed28'
down_revision: Union[str, None] = '007_add_service_featured_slug'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_admin_users_email'), table_name='admin_users')
    op.create_index(op.f('ix_admin_users_email'), 'admin_users', ['email'], unique=True)
    
    # Add columns with nullable=True first, then set default values
    op.add_column('contacts', sa.Column('is_read', sa.Boolean(), nullable=True))
    op.add_column('contacts', sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    
    # Update existing rows with default values
    op.execute("UPDATE contacts SET is_read = FALSE WHERE is_read IS NULL")
    op.execute("UPDATE contacts SET status = 'new' WHERE status IS NULL")
    
    # Now make columns NOT NULL
    op.alter_column('contacts', 'is_read', nullable=False)
    op.alter_column('contacts', 'status', nullable=False)
    op.alter_column('contacts', 'message',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(length=10000),
               existing_nullable=False)
    op.drop_index(op.f('idx_contacts_created_at'), table_name='contacts')
    op.drop_index(op.f('idx_contacts_email'), table_name='contacts')
    op.drop_index(op.f('idx_images_created_at'), table_name='images')
    op.drop_index(op.f('idx_images_entity'), table_name='images')
    op.drop_constraint(op.f('images_project_id_fkey'), 'images', type_='foreignkey')
    op.drop_constraint(op.f('images_service_id_fkey'), 'images', type_='foreignkey')
    op.create_foreign_key(None, 'images', 'projects', ['project_id'], ['id'])
    op.create_foreign_key(None, 'images', 'services', ['service_id'], ['id'])
    op.alter_column('projects', 'description',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(length=50000),
               existing_nullable=False)
    op.alter_column('projects', 'tech_stack',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::character varying[]"))
    op.alter_column('projects', 'project_meta',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('projects', 'challenges',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('projects', 'key_features',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_index(op.f('idx_projects_created_at'), table_name='projects')
    op.drop_index(op.f('idx_projects_featured'), table_name='projects', postgresql_where='(featured = true)')
    op.drop_constraint(op.f('uq_projects_slug'), 'projects', type_='unique')
    op.create_index(op.f('ix_projects_featured'), 'projects', ['featured'], unique=False)
    op.create_index(op.f('ix_projects_slug'), 'projects', ['slug'], unique=True)
    op.alter_column('services', 'slug',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
    op.alter_column('services', 'description',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(length=50000),
               existing_nullable=False)
    op.alter_column('services', 'featured',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('services', 'features',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('services', 'delivery_time',
               existing_type=sa.VARCHAR(),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_index(op.f('idx_services_featured'), table_name='services', postgresql_where='(featured = true)')
    op.drop_index(op.f('idx_services_name'), table_name='services')
    op.drop_constraint(op.f('uq_services_slug'), 'services', type_='unique')
    op.create_index(op.f('ix_services_featured'), 'services', ['featured'], unique=False)
    op.create_index(op.f('ix_services_slug'), 'services', ['slug'], unique=True)
    op.drop_column('services', 'icon_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('icon_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_services_slug'), table_name='services')
    op.drop_index(op.f('ix_services_featured'), table_name='services')
    op.create_unique_constraint(op.f('uq_services_slug'), 'services', ['slug'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_services_name'), 'services', ['name'], unique=False)
    op.create_index(op.f('idx_services_featured'), 'services', ['featured'], unique=False, postgresql_where='(featured = true)')
    op.alter_column('services', 'delivery_time',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('services', 'features',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('services', 'featured',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('services', 'description',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=50000),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('services', 'slug',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
    op.drop_index(op.f('ix_projects_slug'), table_name='projects')
    op.drop_index(op.f('ix_projects_featured'), table_name='projects')
    op.create_unique_constraint(op.f('uq_projects_slug'), 'projects', ['slug'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_projects_featured'), 'projects', ['featured'], unique=False, postgresql_where='(featured = true)')
    op.create_index(op.f('idx_projects_created_at'), 'projects', [sa.literal_column('created_at DESC')], unique=False)
    op.alter_column('projects', 'key_features',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('projects', 'challenges',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('projects', 'project_meta',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('projects', 'tech_stack',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::character varying[]"))
    op.alter_column('projects', 'description',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=50000),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(None, 'images', type_='foreignkey')
    op.drop_constraint(None, 'images', type_='foreignkey')
    op.create_foreign_key(op.f('images_service_id_fkey'), 'images', 'services', ['service_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('images_project_id_fkey'), 'images', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('idx_images_entity'), 'images', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('idx_images_created_at'), 'images', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('idx_contacts_email'), 'contacts', ['email'], unique=False)
    op.create_index(op.f('idx_contacts_created_at'), 'contacts', [sa.literal_column('created_at DESC')], unique=False)
    op.alter_column('contacts', 'message',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=10000),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('contacts', 'status')
    op.drop_column('contacts', 'is_read')
    op.drop_index(op.f('ix_admin_users_email'), table_name='admin_users')
    op.create_index(op.f('idx_admin_users_email'), 'admin_users', ['email'], unique=True)
    # ### end Alembic commands ###
